### ISSUE TITLE
pmass value hardcoded in particles.py

### ISSUE THREAD

**Issue by giadarol** [xsuite/xtrack#34]
The rest of the python code takes constants from scipy.constants
The C code has them hardcoded in constants.h 

We shovel remote the hardcoded values in particles.py to have the same strategy across the python code and then review this whole constants business

**Comment by martinschwinzerl** [comment]
Can we generate `headers/constants.h` from python? Currently there is a constants file here and in xfields and since 
- we are already using code-generation and run-time compilation for interfacing `C <-> Python` and 
- `headers/constants.h` contains only entries that are fundamental mathematical or physical constants that should be consistent with an upstream (either scipy, numpy, pdg, etc.) and 
- the values in `constants.h` can be overridden by compiler flags / macros defined before including `constants.h` 

this should be doable? Also, if we share the code for generating `constants.h` between xtrack, xfields, (potentially xpart?), etc., there is less of a chance of these values eventually getting inconsistent.

**Comment by giadarol** [comment]
> Can we generate `headers/constants.h` from python? Currently there is a constants file here and in xfields and since
> 
>     * we are already using code-generation and run-time compilation for interfacing `C <-> Python` and
> 
>     * `headers/constants.h` contains only entries that are fundamental mathematical or physical constants that should be consistent with an upstream (either scipy, numpy, pdg, etc.) and
> 
>     * the values in `constants.h` can be overridden by compiler flags / macros defined before including `constants.h`
> 
> 
> this should be doable? Also, if we share the code for generating `constants.h` between xtrack, xfields, (potentially xpart?), etc., there is less of a chance of these values eventually getting inconsistent.

Yes, later on we should define a central module in python with all the constants and generate the header for the C code from those

**Comment by giadarol** [comment]
For now I just remove the hardcoded number that can be easily forgotten in favor of scipy (which is easy to grep)

**Comment by giadarol** [comment]
Done for v0.2.0

**Comment by giadarol** [comment]
See PR #40
